apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-green-index
data:
  index.html: |
    <html>
      <head><title>Green Deployment</title></head>
      <body style="background-color:#d4f7dc;">
        <h1>âœ… GREEN Deployment</h1>
        <p>This traffic is coming from GREEN version</p>
      </body>
    </html>
