apiVersion: apps/v1
kind: Deployment
metadata: 
  name: recreate-nginx
spec: 
  replicas: 3
  strategy: 
    type: Recreate
  selector: 
    matchLabels: 
      app: recreate
  template: 
    metadata:
      labels: 
        app: recreate
    spec:    
      containers: 
       - name: nginx
         image: nginx:1.24
         ports: 
          - containerPort: 80


     

