apiVersion: apps.v1
kind: deployment
metadata: 
  name: web
sepc: 
  replicas: 3
  strategy: 
    type: Recreate
  selector: 
    matchLabels: 
      app: recreate
  template: 
    metadata:
      labels: 
        app: recreate
    spec:    
      container: 
       - name: nginx
         image: nginx:1.24
         ports: 
          - containerPort: 80


     

